wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.3
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719575598
    t:
      1:
      - 1
      - 5
      - 9
      - 53
      - 55
      - 103
      2:
      - 1
      - 5
      - 9
      - 53
      - 55
      - 103
      3:
      - 2
      - 23
      - 24
      - 37
      4: 3.9.19
      5: 0.17.3
      8:
      - 3
      - 5
      13: windows-amd64
batch_size:
  desc: null
  value: 6
h_size:
  desc: null
  value: 125
lr:
  desc: null
  value: 1.0008568011822394
n_heads:
  desc: null
  value: 3
neighbor_aggregation:
  desc: null
  value: attention
normalize_edge_weights:
  desc: null
  value: false
