wandb_version: 1

batch_size:
  value: 8
lr:
  value: 8.116913015291744e-05
model:
  value: GCNN_RNN
n_heads:
  value: 1
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: false
num_parameters:
  value: 1
rel_mlp_width:
  value: 2
