wandb_version: 1

batch_size:
  value: 2
lr:
  value: 0.000398117224409824
model:
  value: GRNN
n_heads:
  value: 2
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: false
num_parameters:
  value: 100
rel_mlp_width:
  value: 3
