wandb_version: 1

batch_size:
  value: 2
lr:
  value: 0.009216048677688993
model:
  value: GCNN_RNN
n_heads:
  value: 4
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: true
num_parameters:
  value: 100000
rel_mlp_width:
  value: 2
