wandb_version: 1

batch_size:
  value: 8
lr:
  value: 0.000792535167263797
model:
  value: GCNN_RNN
n_heads:
  value: 4
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: true
num_parameters:
  value: 10000
rel_mlp_width:
  value: 3
