wandb_version: 1

batch_size:
  value: 8
lr:
  value: 0.0003703366468608184
model:
  value: GCNN_RNN
n_heads:
  value: 4
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: false
num_parameters:
  value: 10000
rel_mlp_width:
  value: 3
