wandb_version: 1

batch_size:
  value: 2
lr:
  value: 0.0001716685688420579
model:
  value: GCNN_RNN
n_heads:
  value: 1
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: false
num_parameters:
  value: 1000
rel_mlp_width:
  value: 2
