wandb_version: 1

batch_size:
  value: 8
h_size:
  value: 180
lr:
  value: 0.03809877475875131
model:
  value: GRNN
n_heads:
  value: 4
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: false
rel_mlp_width:
  value: 1
