method: bayes
metric:
  name: val_loss
  goal: minimize
parameters:
  num_parameters:
    values: [100, 1000, 10000, 100000]
  batch_size:
    values: [8]
  lr:
    distribution: log_uniform
    min: -6
    max: -3
  normalize_edge_weights:
    values: [true, false]
  neighbor_aggregation:
    # values: ["mean", "attention", "none"]
    values: ["none"]
  model:
    values: ["GRNN"]
    # values: ["TCN", "GCNN_RNN", "GRNN"]
  n_heads:
    distribution: int_uniform
    min: 1
    max: 4
  rel_mlp_width:
    distribution: int_uniform
    min: 1
    max: 3

