method: bayes
metric:
  name: val_loss
  goal: minimize
parameters:
  h_size:
    distribution: int_uniform
    min: 32
    max: 256
  batch_size:
    values: [2, 4, 6]
  lr:
    distribution: log_uniform
    min: -6
    max: -3
  normalize_edge_weights:
    values: [true, false]
  neighbor_aggregation:
    values: ["mean", "attention"]
  n_heads:
    distribution: int_uniform
    min: 1
    max: 4
