wandb_version: 1

batch_size:
  value: 8
lr:
  value: 0.00020891434038646607
model:
  value: GCNN_RNN
n_heads:
  value: 3
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: false
num_parameters:
  value: 1
rel_mlp_width:
  value: 3
