wandb_version: 1

batch_size:
  value: 8
lr:
  value: 1.1463631617257111e-05
model:
  value: GCNN_RNN
n_heads:
  value: 2
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: true
num_parameters:
  value: 100000
rel_mlp_width:
  value: 2
