wandb_version: 1

batch_size:
  value: 2
lr:
  value: 3.0102398306976537e-05
model:
  value: GCNN_RNN
n_heads:
  value: 1
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: true
num_parameters:
  value: 100000
rel_mlp_width:
  value: 1
