wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.3
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719743005
    t:
      1:
      - 1
      - 5
      - 9
      - 53
      - 55
      - 77
      - 103
      2:
      - 1
      - 5
      - 9
      - 53
      - 55
      - 77
      - 103
      3:
      - 2
      - 23
      - 24
      - 37
      4: 3.9.19
      5: 0.17.3
      8:
      - 3
      - 5
      13: windows-amd64
batch_size:
  desc: null
  value: 2
lr:
  desc: null
  value: 2.3625107765457828e-05
model:
  desc: null
  value: GRNN
n_heads:
  desc: null
  value: 1
neighbor_aggregation:
  desc: null
  value: none
normalize_edge_weights:
  desc: null
  value: true
num_parameters:
  desc: null
  value: 100000
rel_mlp_width:
  desc: null
  value: 1
num_params:
  desc: null
  value: 100000
n_epochs:
  desc: null
  value: 2000
num_train_dates:
  desc: null
  value: 300
num_validation_dates:
  desc: null
  value: 40
input_hor:
  desc: null
  value: 21
pred_hor:
  desc: null
  value: 1
max_grad_norm:
  desc: null
  value: 1
num_lr_steps:
  desc: null
  value: 1
lr_decay:
  desc: null
  value: 1
n_nodes:
  desc: null
  value: 3070
n_features:
  desc: null
  value: 1
profile:
  desc: null
  value: false
min_delta:
  desc: null
  value: 0
patience:
  desc: null
  value: 5
mlp_width:
  desc: null
  value: 1
dev_run:
  desc: null
  value: false
plot_predictions:
  desc: null
  value: true
