wandb_version: 1

batch_size:
  value: 8
lr:
  value: 5.56683316167171e-05
model:
  value: GCNN_RNN
n_heads:
  value: 2
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: false
num_parameters:
  value: 100000
rel_mlp_width:
  value: 1
