wandb_version: 1

batch_size:
  value: 8
lr:
  value: 0.0007129824564112722
model:
  value: GCNN_RNN
n_heads:
  value: 2
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: false
num_parameters:
  value: 1000
rel_mlp_width:
  value: 3
