wandb_version: 1

batch_size:
  value: 8
lr:
  value: 9.38070633611382e-05
model:
  value: GCNN_RNN
n_heads:
  value: 1
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: true
num_parameters:
  value: 100
rel_mlp_width:
  value: 2
