wandb_version: 1

batch_size:
  value: 8
lr:
  value: 0.0005953312915936169
model:
  value: GCNN_RNN
n_heads:
  value: 3
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: false
num_parameters:
  value: 10000
rel_mlp_width:
  value: 1
