wandb_version: 1

batch_size:
  value: 8
h_size:
  value: 208
lr:
  value: 0.009568486744364862
model:
  value: GRNN
n_heads:
  value: 4
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: true
rel_mlp_width:
  value: 2
