wandb_version: 1

batch_size:
  value: 8
h_size:
  value: 232
lr:
  value: 0.020510026534631826
model:
  value: GRNN
n_heads:
  value: 4
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: false
rel_mlp_width:
  value: 1
