wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.3
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719687992
    t:
      1:
      - 1
      - 5
      - 9
      - 53
      - 55
      - 77
      - 103
      2:
      - 1
      - 5
      - 9
      - 53
      - 55
      - 77
      - 103
      3:
      - 23
      - 24
      - 37
      4: 3.9.19
      5: 0.17.3
      8:
      - 3
      - 5
      13: windows-amd64
batch_size:
  desc: null
  value: 8
lr:
  desc: null
  value: 0.0006824372294253888
model:
  desc: null
  value: GCNN_RNN
n_heads:
  desc: null
  value: 3
neighbor_aggregation:
  desc: null
  value: none
normalize_edge_weights:
  desc: null
  value: true
num_parameters:
  desc: null
  value: 100000
rel_mlp_width:
  desc: null
  value: 3
