wandb_version: 1

batch_size:
  value: 8
lr:
  value: 0.006259624090845033
model:
  value: GCNN_RNN
n_heads:
  value: 4
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: false
num_parameters:
  value: 100
rel_mlp_width:
  value: 1
