wandb_version: 1

batch_size:
  value: 8
lr:
  value: 0.00013721723849195196
model:
  value: GCNN_RNN
n_heads:
  value: 1
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: true
num_parameters:
  value: 1000
rel_mlp_width:
  value: 1
