wandb_version: 1

batch_size:
  value: 2
lr:
  value: 2.36961222865758e-05
model:
  value: GRNN
n_heads:
  value: 1
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: true
num_parameters:
  value: 100
rel_mlp_width:
  value: 2
