wandb_version: 1

batch_size:
  value: 2
lr:
  value: 0.0009543302008875908
model:
  value: GRNN
n_heads:
  value: 4
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: true
num_parameters:
  value: 10000
rel_mlp_width:
  value: 1
