wandb_version: 1

batch_size:
  value: 2
lr:
  value: 0.00028738800907304605
model:
  value: GRNN
n_heads:
  value: 3
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: false
num_parameters:
  value: 1000
rel_mlp_width:
  value: 2
