wandb_version: 1

batch_size:
  value: 8
h_size:
  value: 90
lr:
  value: 0.008519406673776013
model:
  value: GRNN
n_heads:
  value: 4
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: true
rel_mlp_width:
  value: 3
