wandb_version: 1

batch_size:
  value: 8
h_size:
  value: 164
lr:
  value: 0.03440969827974963
model:
  value: GRNN
n_heads:
  value: 1
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: false
rel_mlp_width:
  value: 1
