wandb_version: 1

batch_size:
  value: 8
h_size:
  value: 230
lr:
  value: 0.0034108294596605524
model:
  value: GRNN
n_heads:
  value: 2
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: false
rel_mlp_width:
  value: 2
