wandb_version: 1

batch_size:
  value: 2
lr:
  value: 0.00028023583447700544
model:
  value: GRNN
n_heads:
  value: 1
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: false
num_parameters:
  value: 100000
rel_mlp_width:
  value: 2
