wandb_version: 1

batch_size:
  value: 2
lr:
  value: 0.0007520016795156371
model:
  value: GRNN
n_heads:
  value: 3
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: true
num_parameters:
  value: 100
rel_mlp_width:
  value: 3
