wandb_version: 1

batch_size:
  value: 2
lr:
  value: 1.5165097116908377e-05
model:
  value: GRNN
n_heads:
  value: 2
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: false
num_parameters:
  value: 1000
rel_mlp_width:
  value: 3
