wandb_version: 1

batch_size:
  value: 2
lr:
  value: 0.000895563864464658
model:
  value: GRNN
n_heads:
  value: 2
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: true
num_parameters:
  value: 100000
rel_mlp_width:
  value: 2
