wandb_version: 1

batch_size:
  value: 8
h_size:
  value: 181
lr:
  value: 0.00423118921631664
model:
  value: GRNN
n_heads:
  value: 4
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: true
