wandb_version: 1

batch_size:
  value: 8
lr:
  value: 0.0003496949869416955
model:
  value: GCNN_RNN
n_heads:
  value: 2
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: false
num_parameters:
  value: 10000
rel_mlp_width:
  value: 2
