wandb_version: 1

batch_size:
  value: 8
lr:
  value: 3.424301162840338e-05
model:
  value: GCNN_RNN
n_heads:
  value: 4
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: true
num_parameters:
  value: 1
rel_mlp_width:
  value: 2
