wandb_version: 1

batch_size:
  value: 8
h_size:
  value: 115
lr:
  value: 0.014919429333382375
model:
  value: GRNN
n_heads:
  value: 2
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: false
rel_mlp_width:
  value: 2
