wandb_version: 1

batch_size:
  value: 8
h_size:
  value: 43
lr:
  value: 0.0039299604134099865
model:
  value: GRNN
n_heads:
  value: 2
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: true
rel_mlp_width:
  value: 3
