wandb_version: 1

batch_size:
  value: 8
h_size:
  value: 63
lr:
  value: 0.006749434881066713
model:
  value: GRNN
n_heads:
  value: 3
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: false
rel_mlp_width:
  value: 1
