wandb_version: 1

batch_size:
  value: 8
h_size:
  value: 147
lr:
  value: 0.039585038167094994
model:
  value: GRNN
n_heads:
  value: 3
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: true
rel_mlp_width:
  value: 3
