wandb_version: 1

batch_size:
  value: 8
h_size:
  value: 115
lr:
  value: 0.012613250483649368
model:
  value: GRNN
n_heads:
  value: 3
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: false
rel_mlp_width:
  value: 1
