wandb_version: 1

batch_size:
  value: 2
lr:
  value: 0.00012089737018377042
model:
  value: GCNN_RNN
n_heads:
  value: 1
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: false
num_parameters:
  value: 100
rel_mlp_width:
  value: 1
