wandb_version: 1

batch_size:
  value: 8
h_size:
  value: 174
lr:
  value: 0.01711631517689379
model:
  value: GRNN
n_heads:
  value: 1
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: false
rel_mlp_width:
  value: 2
