wandb_version: 1

batch_size:
  value: 8
h_size:
  value: 147
lr:
  value: 0.01508428071287016
model:
  value: GRNN
n_heads:
  value: 2
neighbor_aggregation:
  value: none
normalize_edge_weights:
  value: false
rel_mlp_width:
  value: 1
